### ISSUE TITLE
Username field blank after authorization

### ISSUE THREAD

**Issue by bigskillet** [codingbadger/instant-tokens.com#5]
The username field is blank after authorization making it difficult to differentiate between authorize accounts.

**Comment by codingbadger** [comment]
Hello, 

Thanks for reporting this.

I have released a few updates to the site this morning, one of which is the ability to refresh the username value from Instagram.

![image](https://user-images.githubusercontent.com/1089628/88639440-b35b0980-d0b4-11ea-9f5a-17d7b29e0ee2.png)

Cheers

**Comment by bigskillet** [comment]
Hmmm, it's not refreshing for me.
![image](https://user-images.githubusercontent.com/682013/88676844-2fa01d80-d0b2-11ea-958c-c521138062dd.png)

**Comment by codingbadger** [comment]
Hey, 

Looks like the Instagram API is returning an error:

`{
    "error": {
        "message": "Unsupported get request. Object with ID '17841XXXXXXXXXXX' does not exist, cannot be loaded due to missing permissions, or does not support this operation",
        "type": "IGApiException",
        "code": 100,
        "error_subcode": 33,
        "fbtrace_id": "A6EUPxxxxxxxxxxxxx"
    }
}`

I'll try and see what those error codes mean. Trying to hunt down any info (other than the basic operations) for this API is proving difficult.

Cheers

**Comment by codingbadger** [comment]
Something doesn't seem right with the setup, can you add the authorisation again?

**Comment by bigskillet** [comment]
I logged into Instagram and revoked the access, but it's not removing the authorization. I also tried reauthorizing, but it's still showing the old authorization.

**Comment by codingbadger** [comment]
Hello,

Hmm very strange, I have manually cleared out the authorisation so you should be good to go.

Thanks

Barry


________________________________

**Comment by bigskillet** [comment]
It was cleared, but reauthorizing didn't fix the username issue. I tried removing access again after that, then reauthorizing, and it's not clearing the old authorization again.

**Comment by codingbadger** [comment]
Hello, 

I checked the logs and the Instagram API is returning the same error as before. I will reach out to them and see if they can help.

If you drop me an email (barry AT codingbadger DOT com)  with the username I can manually update it for you. 

Thanks

**Comment by codingbadger** [comment]
This has been raised as a bug already with Facebook https://developers.facebook.com/support/bugs/320668765776353/

This is the exact same situation so I have subscribed to this ticket to get future updates.
